import type { Flow } from '../types'

// "한 턴의 생애": 개념 진입 → 캐시 조회 → (미스) 상한·생성·저장 → 질문 → 채점 → 힌트 → 다음.
export const turnLifecycle: Flow = {
  stages: [
    { id: 'browser', label: '브라우저', color: '#3b82f6' },
    { id: 'edge', label: 'Edge Functions', color: '#8b5cf6' },
    { id: 'db', label: 'Postgres', color: '#0ea5e9' },
    { id: 'llm', label: 'Gemini flash', color: '#f59e0b' },
  ],
  nodes: [
    { id: 'b-enter', stage: 'browser', title: '개념 진입', subtitle: '순회·사다리' },
    { id: 'b-question', stage: 'browser', title: '질문 표시' },
    { id: 'b-answer', stage: 'browser', title: '답변 입력' },
    { id: 'e-generate', stage: 'edge', title: 'generate' },
    { id: 'e-grade', stage: 'edge', title: 'grade' },
    { id: 'e-hint', stage: 'edge', title: 'hint' },
    { id: 'db-cache', stage: 'db', title: 'question_cache', subtitle: '공유 캐시' },
    { id: 'db-usage', stage: 'db', title: 'grade_usage', subtitle: '일일 상한' },
    { id: 'db-events', stage: 'db', title: 'grade_events', subtitle: '사용량 미터' },
    { id: 'g-llm', stage: 'llm', title: 'Gemini flash', subtitle: 'LLM 질문/채점' },
  ],
  steps: [
    { title: '1. 개념 진입', activeNodes: ['b-enter'], edges: [],
      note: '순회 엔진이 다음 개념(노드)을 고르고, 그 노드의 현재 계단 질문을 요청한다.' },
    { title: '2. 캐시 먼저 조회', activeNodes: ['e-generate', 'db-cache'],
      edges: [{ from: 'b-enter', to: 'e-generate' }, { from: 'e-generate', to: 'db-cache' }],
      note: 'generate는 LLM보다 먼저 question_cache를 본다. 히트면 여기서 끝(토큰 0).' },
    { title: '3. 캐시 미스 → 상한 예약', activeNodes: ['e-generate', 'db-usage'],
      edges: [{ from: 'e-generate', to: 'db-usage' }],
      note: '미스일 때만 일일 상한을 원자적으로 예약(reserve). 실패는 나중에 환불.' },
    { title: '4. Gemini가 질문 생성', activeNodes: ['e-generate', 'g-llm'],
      edges: [{ from: 'e-generate', to: 'g-llm' }, { from: 'g-llm', to: 'e-generate' }],
      note: '노트를 근거로 이 계단의 질문 + 모범답안을 만든다.' },
    { title: '5. 캐시에 저장 + 미터 로깅', activeNodes: ['e-generate', 'db-cache', 'db-events'],
      edges: [{ from: 'e-generate', to: 'db-cache' }, { from: 'e-generate', to: 'db-events' }],
      note: '생성 결과를 캐시에 넣어 다음 사용자는 토큰 0. 호출 1건을 미터에 기록.' },
    { title: '6. 질문 표시', activeNodes: ['e-generate', 'b-question'],
      edges: [{ from: 'e-generate', to: 'b-question' }],
      note: '브라우저가 질문을 렌더한다.' },
    { title: '7. 답변 → 채점', activeNodes: ['b-answer', 'e-grade', 'g-llm'],
      edges: [{ from: 'b-answer', to: 'e-grade' }, { from: 'e-grade', to: 'g-llm' }],
      note: '사용자 답변을 grade가 Gemini로 1~5점 채점.' },
    { title: '8. 막히면 힌트', activeNodes: ['b-answer', 'e-hint', 'g-llm'],
      edges: [{ from: 'b-answer', to: 'e-hint' }, { from: 'e-hint', to: 'g-llm' }],
      note: '점수가 낮으면(≤2) 답변 기반 힌트를 한 줄 준다.' },
    { title: '9. 다음 개념으로', activeNodes: ['e-grade', 'b-enter'],
      edges: [{ from: 'e-grade', to: 'b-enter' }],
      note: '점수가 다음 계단/노드를 정한다(advanceLadder → 순회).' },
  ],
}
